modules/core/src/main/java/org/apache/synapse/util/MessageHelper.java, modules/core/src/test/java/org/apache/synapse/util/MessageHelperTest.java
When a From value is set in the message context (e.g. with MessageContext.setFrom) before it is sent to an endpoint the value isn't used in the resulting request. This is due to the fact that the Axis2FlexibleMEPClient clones the message context before sending it and the MessageHelper.clonePartially doesn't copy the From value from the source message context to the cloned message context.
=> SYNAPSE-1109: copy wsa:From value when creating request context

modules/core/src/main/java/org/apache/synapse/Axis2SynapseController.java, modules/core/src/main/java/org/apache/synapse/core/axis2/ProxyService.java
When a proxy service is started the Axis2 Observers aren't notified.
This is due to the fact that the proxy services are only loaded by the
Axis2 Synapse controller and not started. Inline in, out and fault
sequences are not initialized, since that happens when a service is
started.
By starting the proxy services explicitly in the Axis2 Synapse
controller the sequences are properly initialized and the Axis2
Observers are notified.
=> Notify observers when starting proxy services

modules/core/src/main/java/org/apache/synapse/core/axis2/ProxyService.java
When the addressing or security module is engaged on the proxy service
the Axis2 Observers aren't notified. This is due to the fact that the
wrong engageModule method is invoked on the AxisService.
By invoking the correct engageModule method on the AxisService the Axis2
Observers are notified when a module is engaged on a proxy service.
=> Notify observers when engaging proxy modules

modules/transports/core/nhttp/src/main/java/org/apache/synapse/transport/passthru/ClientWorker.java, modules/transports/core/nhttp/src/main/java/org/apache/synapse/transport/passthru/ServerWorker.java
MessageContext class store messageContext object in a ThreadLocalVariable where it doesn't clear created ThreadLocal variables properly. Therefore synapse passthrough threads contain created the Theadlocal variable which refers to the created soap envelope during the mediation level. Because of the retained ThreadLocal variables, Passthrough threads consumes a huge amount of memory which leads to OOM.
=> Fix SYNAPSE-1106

modules/core/src/main/java/org/apache/synapse/Axis2SynapseController.java, modules/core/src/main/java/org/apache/synapse/ServerConfigurationInformation.java, modules/core/src/main/java/org/apache/synapse/ServerConfigurationInformationFactory.java, modules/core/src/main/java/org/apache/synapse/core/SynapseEnvironment.java, modules/core/src/main/java/org/apache/synapse/core/axis2/Axis2SynapseEnvironment.java, modules/core/src/main/java/org/apache/synapse/mediators/builtin/LogMediator.java, modules/distribution/src/main/bin/synapse.bat, modules/distribution/src/main/bin/synapse.sh
Consider the below Proxy service in which I have configured the log-mediator to print logs only when the category is set to DEBUG. However, there is no way to start the server with log-mediator debug logs enabled. 
Only way to print the property values inside the log mediator is by configuring debug mode for the log -mediator class in the log4j.properties. But this is wrong because aforementioned configuration is there for the implementer of log-mediator but not for the synapse user.
```xml
 <proxy xmlns="http://ws.apache.org/ns/synapse"
name="test"
transports="http,https"
statistics="disable"
trace="disable"
startOnLoad="true">
<target>
<inSequence>
<log category="DEBUG">
<property name="someproperty" value="somevalue"/>
</log>
<respond/>
</inSequence>
</target>
<description/>
</proxy> …
```
=> Add an improvement to log-mediator

README.md
CI build runs for a particular pull request. Failure or the success of the CI build does not reflect the build state of the entire source repository. So we need to remove that from the main readme file.
=> Remove CI badge from readme

.github/workflows/build_cron.yml
This will run the daily build on latest windows apart from running it on latest linux os.
=> Add windows runner to workflow

modules/core/src/main/java/org/apache/synapse/SynapseConstants.java, modules/core/src/main/java/org/apache/synapse/message/processors/MessageProcessorConsents.java, modules/core/src/main/java/org/apache/synapse/message/processors/forward/ForwardingJob.java, modules/core/src/main/java/org/apache/synapse/message/processors/forward/ForwardingProcessorConstants.java
At the moment, current MFP implementation does not support retrying based on HTTP status codes. It only supports retrying for transport level failures but not for application level failures. As you know, in HTTP protocol, application level failures are distinguished using different status codes. In the case of MFP, it is important to be able to retry for 5xx server errors. But there also could be rare occasions in which retrying for 4xx and 3xx are useful. Especially when dealing with servers that do not follow HTTP protocol exactly as it is.
Therefore, I have improved MFP implementation to support retrying based on the returned HTTP status code as well. Say, a user wants to retry for HTTP status codes 500 and 504 but not for any other HTTP status code. In that case user can configure the …
=> Improve Message Forwarding Processor (MFP) to support HTTP status codes

modules/core/src/main/java/org/apache/synapse/message/processors/MessageProcessorConstants.java, modules/core/src/main/java/org/apache/synapse/message/processors/ScheduledMessageProcessor.java, modules/core/src/main/java/org/apache/synapse/message/processors/forward/ForwardingJob.java, modules/core/src/main/java/org/apache/synapse/message/processors/resequence/ResequencingJob.java, modules/core/src/main/java/org/apache/synapse/message/processors/sampler/SamplingJob.java
Hi All,
I have fixed the typo in the class as follows,
`MessageProcessorConsents` -> `MessageProcessorConstants`
=> Fix the typo in the class name

.github/workflows/build_cron.yml
At the moment daily build only runs on ubuntu and windows. This PR adds mac-os to the list.
=> Add mac-os runner for the daily build

modules/core/src/main/java/org/apache/synapse/message/processors/forward/ForwardingJob.java
Hi All,
This PR does the $subject and in the process I have fixed two issues as well. 
Programmers spend more time to reading code and less time on writing code. Therefore, it is needless to say that having readable code is essential in any project. `ForwardingJob` class was actually the opposite of this (forgive me for saying this) and it is very hard to read the code do new modification. Making the code vulnerable for regression issues. 
Therefore, I have refactored the code starting the basic principle of functions doing one and only one thing. In the processes I have moved some variables into class variables as actually control the state of the `ForwadingJob`. Also, code abstraction done in a way that, reader starts with the highest abstraction of the concept and then drill down to …
=> Refactor ForwardingJob class and fix few issues

.github/workflows/build_cron.yml
Add the moment workflow configured to do daily builds only runs on java 8. This PR change the workflow to include java 7 along with java 8.
=> Add Java 7 to build matrix

modules/core/src/main/java/org/apache/synapse/message/processors/forward/ForwardingJob.java, modules/core/src/main/java/org/apache/synapse/message/processors/forward/ForwardingProcessorConstants.java
At the moment Message Processor only support one interval for both fetching messages from the store and retrying when there is a failure. But, IMO, these are two different concepts and deserve two different configurations. Therefore, this PR introduces the new retry interval as follows,
```<parameter name="retry.interval">10000</parameter>```
This will allow the user to control the speed of retry when there is a failure. 
Please note that after the change I have re-tested all the scenarios such as,
**Out Only Scenario**
- Success scenario
- Retry scenario
- Max delivery scenario
- Max delivery drop scenario
- Invoking Deactivate scenario
**Response Scenario**
- Success scenario
- Retry scenario
- Retry on application level failure scenario
- Invoking reply sequence scenario
- Invoking …
=> Add retry interval feature

.github/workflows/build_pull.yml
At the moment the build that runs for each PR only runs on ubuntu and Java 8. With this PR I have added windows and mac to the build along with Java 7.
=> Add different OSs and JDKs

modules/core/src/main/java/org/apache/synapse/message/processors/forward/ForwardingJob.java
At the moment, when there is a failure in Message Processor (i.e. Connection refused) fault sequence is not invoked in `OUT_ONLY` scenario. This issue is fixed with this PR.
=> Fix the issue of not invoking fault-sequence

modules/documentation/src/site/xdoc/userguide/samples/sample705.xml
This PR includes the documentation for `consume.all` property. For more details please refer to #46.
=> Add documentation for consume.all property of Message Forwarding Processor

modules/core/src/main/java/org/apache/synapse/message/processors/forward/ForwardingJob.java, modules/core/src/main/java/org/apache/synapse/message/processors/forward/ForwardingProcessorConstants.java
Current behavior of the Message Forwarding Processor is to consume all the messages at once. For instance, say, the Message Forwarding Processor is configured to run every 10 seconds and the Message store is filled with 5 messages within the 10 second gap. In such a situation, Message Forwarding Processor consumes all 5 messages and try to send it to back-end as fast as possible. I think this behavior is not optimal. The purpose of Message Forwarding Processor it to send messages to the back-end in a controlled rate. So that the back-end server can handle the load. IMO, ideal behavior should be to consume one message at a time and try to send it to the back-end as per the configured interval. 
I have implemented this feature by introducing the below configuration to Message Processor. …
=> Add consume one message at a time feature

.github/workflows/build_cron.yml, .github/workflows/build_pull.yml
At the moment both daily build and the PR builds are failing due to a SSL issue. This issue is only seen when the build is run with Java 8 which is provided by setup-java github action. I am further looking into this issue. In the mean time I have removed Java 8 build.
Please note that  the same issue is not there when building with Java 8. So this seems be an issue specific to the github environment.
=> Fix the build

modules/core/src/main/java/org/apache/synapse/config/xml/MessageProcessorFactory.java, modules/core/src/main/java/org/apache/synapse/config/xml/MessageProcessorSerializer.java, modules/core/src/main/java/org/apache/synapse/message/processors/AbstractMessageProcessor.java, modules/core/src/main/java/org/apache/synapse/message/processors/MessageProcessor.java, modules/core/src/main/java/org/apache/synapse/message/processors/ScheduledMessageProcessor.java, modules/core/src/main/java/org/apache/synapse/message/processors/forward/ForwardingJob.java
Now the target endpoint associated with Message Forwarding Processor can be given as an attribute of the Message Forwarding Processor config as below.
```xml
<messageProcessor class="org.apache.synapse.message.processors.forward.ScheduledMessageForwardingProcessor" name="ScheduledProcessor" messageStore="MyStore" targetEndpoint="StockQuoteServiceEp">
<parameter name="interval">10000</parameter>
<parameter name="max.deliver.attempts">3</parameter>
<parameter name="max.deliver.drop">true</parameter>
<parameter name="retry.http.status.codes">500, 504</parameter>
<parameter name="retry.interval">1000</parameter>
<parameter name="consume.all">false</parameter>
</messageProcessor>
```
Therefore we no longer require the below property to configure Message Forwarding Processor. 
```xml
<property …
```
=> Improving how Target Endpoint is Associated with Message Forwarding Processor

pom.xml
Bump deprecated JDK version (1.6) in root pom.xml to 1.7
Update `java.version` field in pom.xml file
N/A
On JDK 1.7, Ubuntu 20.04 testing environment
=> Bump JDK version

.gitpod.Dockerfile, .gitpod.yml, README.md
Add Gitpod integration to Apache Synapse project. 
Gitpod enables development to be done on a cloud VS Code IDE with access to a full Linux terminal.
The config files (gitpod.yml and gitpod.Dockerfile) were added 
- _Unit tests_
N/A
- _Integration tests_
N/A
- Java version 1.8.0_265
- Ubuntu 20.04
A Notion document detailing related documentation can be found [here](https://typical-reading-1a7.notion.site/Gitpod-docs-801b93b7857140d8942d03e82c071d09).
=> Add Gitpod integration to project

modules/core/src/test/java/org/apache/synapse/config/xml/endpoints/LoadBalanceEndpointSerializationTest.java, pom.xml
Add environment variable injection capability to LoadBalance endpoints.
Amended `AddressEndpointFactory` classes to extract environment variables via `System.getenv()` based on `$SYSTEM` prefix presence in the Synapse config XML URI elements.
- Unit tests 
Covers related code written in abstract class `EndpointFactory`.
- Integration tests
N/A
Builds on the work done on PR https://github.com/apache/synapse/pull/55
- Java version 1.8.0_141
- Ubuntu 20.04
=> Add environment variable injection for LoadBalance endpoints
